token: ""

guild_id: 123456789

mod_log: 123456798

owner_id: 123456789

emoji_ignore_channels:
    #Channels to ignore when counting emojis
    -123456789

spoiler_channels:
    # Channel ids to check
    - 123456789

filter_channels:
    #channel ids to filter
    - 123456789

filter_allowed:
    - ".iam Clover"
    - ".iam Member"

# Wait time in seconds (default 10 min)
wait_time: 600
